name: CadZinho CI

on: workflow_dispatch

env:
  MAJOR: 0
  MINOR: 4
  MAN: 0
  YEAR: 2023
  
jobs:
  up-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Update version in information files
        run: |
          sed -i -e "/CZ_VERSION/s/[[:digit:]]\{4\}/$YEAR/" \
            -e "/CZ_VERSION/s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/$MAJOR.\2.\3/" \
            -e "/CZ_VERSION/s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.$MINOR.\3/" \
            -e "/CZ_VERSION/s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.\2.$MAN/" \
            ./src/dxf.h
          sed -i -e "/Comments/s/[[:digit:]]\{4\}/$YEAR/" \
            -e "/FILEVERSION/s/\([[:digit:]]\+\),\([[:digit:]]\+\),\([[:digit:]]\+\),0/$MAJOR,\2,\3,0/" \
            -e "/FILEVERSION/s/\([[:digit:]]\+\),\([[:digit:]]\+\),\([[:digit:]]\+\),0/\1,$MINOR,\3,0/" \
            -e "/FILEVERSION/s/\([[:digit:]]\+\),\([[:digit:]]\+\),\([[:digit:]]\+\),0/\1,\2,$MAN,0/" \
            -e "/PRODUCTVERSION/s/\([[:digit:]]\+\),\([[:digit:]]\+\),\([[:digit:]]\+\),0/$MAJOR,\2,\3,0/" \
            -e "/PRODUCTVERSION/s/\([[:digit:]]\+\),\([[:digit:]]\+\),\([[:digit:]]\+\),0/\1,$MINOR,\3,0/" \
            -e "/PRODUCTVERSION/s/\([[:digit:]]\+\),\([[:digit:]]\+\),\([[:digit:]]\+\),0/\1,\2,$MAN,0/" \
            -e "/LegalCopyright/s/[[:digit:]]\{4\}/$YEAR/" \
            -e "/FileVersion/s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/$MAJOR.\2.\3/" \
            -e "/FileVersion/s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.$MINOR.\3/" \
            -e "/FileVersion/s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.\2.$MAN/" \
            -e "/ProductVersion/s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/$MAJOR.\2.\3/" \
            -e "/ProductVersion/s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.$MINOR.\3/" \
            -e "/ProductVersion/s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.\2.$MAN/" \
            ./windows/cz.rc
          sed -i -e "/NSHumanReadableCopyright/,+1s/[[:digit:]]\{4\}/$YEAR/" \
            -e "/CFBundleShortVersionString/,+1s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/$MAJOR.\2.\3/" \
            -e "/CFBundleShortVersionString/,+1s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.$MINOR.\3/" \
            -e "/CFBundleShortVersionString/,+1s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.\2.$MAN/" \
            -e "/CFBundleVersion/,+1s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/$MAJOR.\2.\3/" \
            -e "/CFBundleVersion/,+1s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.$MINOR.\3/" \
            -e "/CFBundleVersion/,+1s/\([[:digit:]]\+\).\([[:digit:]]\+\).\([[:digit:]]\+\)/\1.\2.$MAN/" \
            ./macos/CadZinho.app/Contents/Info.plist
      - name: Commit
        run: |
          git config --global user.name 'zecruel'
          git config --global user.email 'zecruel@users.noreply.github.com'
          git add .
          git commit -m "Update version to $MAJOR.$MINOR.$MAN - $YEAR"
          git push
        continue-on-error: true

  linux-build:
    needs: up-version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sudo apt-get install --yes libsdl2-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev fuse libfuse2
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz
    - name: extract lua
      run: tar zxf lua-5.4.4.tar.gz
    - name: remove main in lua
      run: rm lua-5.4.4/src/lua.c lua-5.4.4/src/luac.c
    - name: copy lua sources 
      run: cp lua-5.4.4/src/* ./src/
    - name: get make file
      run: cp linux/Makefile ./Makefile
    - name: make
      run: make
    - name: download AppImageTool
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
        target: .
    - name: download AppImage asset
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64"
        target: .
    - name: configure AppImageKit
      run: |
        mkdir CadZinho.AppDir
        mkdir CadZinho.AppDir/usr/
        mkdir CadZinho.AppDir/usr/lib
        mkdir CadZinho.AppDir/usr/bin
        mkdir CadZinho.AppDir/usr/bin/share
        mkdir CadZinho.AppDir/usr/bin/share/cadzinho
        mv AppRun-x86_64 CadZinho.AppDir/AppRun
        chmod u+x ./CadZinho.AppDir/AppRun
        cp ./linux/cadzinho.desktop ./CadZinho.AppDir
        cp ./linux/cadzinho.png ./CadZinho.AppDir
        cp ./cadzinho ./CadZinho.AppDir/usr/bin
        cp -r ./lang/ ./CadZinho.AppDir/usr/bin/share/cadzinho/
        cp $(ldd cadzinho | grep -o '\W/[^ ]*' | grep 'SDL2\|GLEW\|decor') ./CadZinho.AppDir/usr/lib
        chmod u+x ./appimagetool-x86_64.AppImage
        ./appimagetool-x86_64.AppImage CadZinho.AppDir
    - name: create archive
      run: |
        zip -r linux_appimage CadZinho-x86_64.AppImage LICENSE.txt
    - name: regular linux package
      run: |
        mkdir ./linux/CadZinho/share/cadzinho
        cp ./cadzinho ./linux/CadZinho
        cp ./LICENSE.txt ./linux/CadZinho/share/cadzinho
        cp -r ./lang/ ./linux/CadZinho/share/cadzinho/
        cd ./linux/CadZinho
        zip -r linux *
    - run: cp ./linux/CadZinho/linux.zip ./
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: |
          linux_appimage.zip
          linux.zip
        retention-days: 5
        
  macos-build:
    needs: up-version
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: brew install sdl2 lua mesa-glu glew dylibbundler
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz
    - name: extract lua
      run: tar zxf lua-5.4.4.tar.gz
    - name: remove main in lua
      run: rm lua-5.4.4/src/lua.c lua-5.4.4/src/luac.c
    - name: copy lua sources 
      run: cp lua-5.4.4/src/* ./src/
    - name: get make file
      run: cp macos/Makefile ./Makefile
    - name: make
      run: make
    - run: mkdir ./macos/CadZinho.app/Contents/MacOS
    - run: cp ./cadzinho ./macos/CadZinho.app/Contents/MacOS/cadzinho
    - run: cp -r ./lang/ ./macos/CadZinho.app/Contents/Resources/lang/
    - name: fix dependencies
      run: dylibbundler -od -b -x ./macos/CadZinho.app/Contents/MacOS/cadzinho -d ./macos/CadZinho.app/Contents/libs/
    - name: create archive
      run: |
        cp LICENSE macos
        cd macos
        zip -r macos ./CadZinho.app/ LICENSE.txt
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: macos/macos.zip
        retention-days: 5
  
  windows-build:
    needs: up-version
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest

    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
          update: true
          install: >-
            base-devel
            git
            gcc
            make
            p7zip
            mingw-w64-x86_64-toolchain
            mingw64/mingw-w64-x86_64-SDL2
            mingw64/mingw-w64-x86_64-glew
    - uses: actions/checkout@v3
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz
    - name: extract lua
      run: tar zxf lua-5.4.4.tar.gz
    - name: remove main in lua
      shell: cmd
      run: |
        cd lua-5.4.4\src
        del lua.c 
        del luac.c
    - name: copy lua sources 
      run: cp ./lua-5.4.4/src/* ./src/
    - name: get make file and resources
      run: cp windows/* ./
    - name: make
      run: make
    - run: |
        mkdir CadZinho
        cp cadzinho.exe CadZinho/
        cp -r ./lang/ CadZinho/
        cp windows/cadzinho.ico CadZinho/
        cp /mingw64/bin/SDL2.dll CadZinho/
        cp /mingw64/bin/glew32.dll CadZinho/
        cp LICENSE.txt CadZinho/
    - name: create archive
      run: 7z a windows.zip CadZinho
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: windows.zip
        retention-days: 5
  msvc-build:
    needs: up-version
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz
    - name: extract lua
      run: tar zxf lua-5.4.4.tar.gz
    - name: remove main in lua
      shell: cmd
      run: |
        cd lua-5.4.4\src
        del lua.c 
        del luac.c
    - name: copy lua sources 
      run: cp ./lua-5.4.4/src/* ./src/
    - name: download glew
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0-win32.zip"
        target: .
    - name: Unzip glew
      shell: cmd
      run: |
        7z x -y glew-2.2.0-win32.zip
    - name: Download SDL2
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/libsdl-org/SDL/releases/download/release-2.26.4/SDL2-devel-2.26.4-VC.zip"
        target: .
    - name: Unzip SDL2
      shell: cmd
      run: |
        7z x -y SDL2-devel-2.26.4-VC.zip
    - run: |
        mkdir ./glew-2.2.0/include/SDL2
        mkdir ./CadZinho
        cp ./SDL2-2.26.4/include/* ./glew-2.2.0/include/SDL2/
    - name: get make file and resources
      run: cp windows/* ./

    - uses: ilammy/msvc-dev-cmd@v1.12.1
    - name: Build using CL.EXE
      run: nmake WIN64=1 -f Makefile.msvc
    - run: |
        cp windows/cadzinho.ico CadZinho/
        cp ./SDL2-2.26.4/lib/x64/SDL2.dll CadZinho/
        cp ./glew-2.2.0/bin/Release/x64/glew32.dll CadZinho/
        cp ./cadzinho.exe CadZinho/
        cp -r ./lang/ CadZinho/
        cp LICENSE.txt CadZinho/
    - name: create archive
      run: 7z a windows_msvc.zip CadZinho
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: windows_msvc.zip
        retention-days: 5
        
  emscripten-built:
    needs: up-version
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: configure SDK
      uses: mymindstorm/setup-emsdk@v12
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz
    - name: extract lua
      run: tar zxf lua-5.4.4.tar.gz
    - name: remove main in lua
      run: rm lua-5.4.4/src/lua.c lua-5.4.4/src/luac.c
    - name: copy lua sources 
      run: cp lua-5.4.4/src/* ./src/
    - name: clear samples
      run: |
        rm samples/*.pdf
        rm samples/*.svg
        rm samples/*.ps
        rm samples/*.jpg
    - name: get make and resources files
      run: |
        cp emscripten/Makefile ./Makefile
        cp emscripten/shell_minimal.html ./shell_minimal.html
    - name: make
      run: make
    - name: create archive
      run: |
        zip -r emscripten cadzinho.js cadzinho.wasm cadzinho.html cadzinho.data
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: emscripten.zip
        retention-days: 5
  release:
    needs: [linux-build, macos-build, windows-build, msvc-build, emscripten-built]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: uploads
      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.MAN }}
          draft: true
          files: |
            linux.zip
            linux_appimage.zip
            macos.zip
            windows.zip
            windows_msvc.zip
            emscripten.zip

