name: Test2

on: workflow_dispatch

env:
  MAJOR: 0
  MINOR: 2
  MAN: 1
  YEAR: 2023
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: configure
        run: gem install fpm
      - run: fpm --version
