name: Test

on: workflow_dispatch

env:
  MAJOR: 0
  MINOR: 4
  MAN: 0
  YEAR: 2023
  LUA_V: 5.4.6
  MESA_V: 23.1.1
  GLEW_V: 2.2.0
  SDL_V: 2.26.5

jobs:
  win:
   runs-on: windows-latest

   steps:
    - uses: actions/checkout@v3
    
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-${{ env.LUA_V }}.tar.gz
    - name: extract lua
      run: tar zxf lua-${{ env.LUA_V }}.tar.gz
    - name: remove main in lua
      shell: cmd
      run: |
        cd lua-${{ env.LUA_V }}\src
        del lua.c 
        del luac.c
    - name: copy lua sources 
      run: cp ./lua-${{ env.LUA_V }}/src/* ./src/
    - name: download glew
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/nigels-com/glew/releases/download/glew-${{ env.GLEW_V }}/glew-${{ env.GLEW_V }}-win32.zip"
        target: .
    - name: Unzip glew
      shell: cmd
      run: |
        7z x -y glew-${{ env.GLEW_V }}-win32.zip
    - name: Download SDL2
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/libsdl-org/SDL/releases/download/release-${{ env.SDL_V }}/SDL2-devel-${{ env.SDL_V }}-VC.zip"
        target: .
    - name: Unzip SDL2
      shell: cmd
      run: |
        7z x -y SDL2-devel-${{ env.SDL_V }}-VC.zip
    - name: download mesa3d
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/pal1000/mesa-dist-win/releases/download/${{ env.MESA_V }}/mesa3d-${{ env.MESA_V }}-release-msvc.7z"
        target: .
    - name: Unzip mesa3d
      shell: cmd
      run: |
        7z x -y mesa3d-${{ env.MESA_V }}-release-msvc.7z
        ls
    - run: |
        mkdir ./glew-${{ env.GLEW_V }}/include/SDL2
        mkdir ./CadZinho
        cp ./SDL2-${{ env.SDL_V }}/include/* ./glew-${{ env.GLEW_V }}/include/SDL2/
        mv ./SDL2-${{ env.SDL_V }} ./SDL2
        mv ./glew-${{ env.GLEW_V }} ./glew
        ls -R ./glew/
        
    - name: get make file and resources
      run: cp windows/* ./

    - uses: ilammy/msvc-dev-cmd@v1.12.1
    - name: Build using CL.EXE
      run: nmake WIN64=1 -f Makefile.msvc
    - run: |
        cp windows/cadzinho.ico CadZinho/
        cp ./SDL2/lib/x64/SDL2.dll CadZinho/
        cp ./glew/bin/Release/x64/glew32.dll CadZinho/
        cp ./cadzinho.exe CadZinho/
        cp -r ./lang/ CadZinho/
        cp x64/opengl32.dll CadZinho/
        cp x64/libgallium_wgl.dll CadZinho/
        cp x64/libglapi.dll CadZinho/
        cp x64/dxil.dll CadZinho/
        cp LICENSE.txt CadZinho/
        cp cadzinho.wxs CadZinho/
    - name: create MSI installer
      uses: utilitywarehouse/ghaction-wix@v1
      with:
        name: cadzinho
        sourceFiles: CadZinho/component.wxs
        outputDir: CadZinho
        architecture: x64
    - name: create archive
      run: 7z a windows_msvc.zip CadZinho
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: windows_msvc.zip
        retention-days: 5
