name: Test2

on: workflow_dispatch

env:
  MAJOR: 0
  MINOR: 5
  MAN: 0
  YEAR: 2024
  LUA_V: 5.4.6
  MESA_V: 23.1.1
  GLEW_V: 2.2.0
  SDL_V: 2.30.0
  SDL_NET_V: 2.2.0
  
jobs:
 test:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4.1.1
    - name: configure SDK
      uses: mymindstorm/setup-emsdk@v14
    - name: download lua source
      uses: suisei-cn/actions-download-file@v1.6.0
      with:
        url: "http://www.lua.org/ftp/lua-${{ env.LUA_V }}.tar.gz"
        target: .
    - name: extract lua
      run: tar zxf lua-${{ env.LUA_V }}.tar.gz
    - name: remove main in lua
      run: rm lua-${{ env.LUA_V }}/src/lua.c lua-${{ env.LUA_V }}/src/luac.c
    - name: copy lua sources 
      run: cp lua-${{ env.LUA_V }}/src/* ./src/
    - name: clear samples
      run: |
        rm samples/*.pdf
        rm samples/*.svg
        rm samples/*.ps
        rm samples/*.jpg
    - name: get make and resources files
      run: |
        cp emscripten/Makefile ./Makefile
        cp emscripten/shell_minimal.html ./shell_minimal.html
    - name: make
      run: make
    - name: create archive
      run: |
        zip -r emscripten cadzinho.js cadzinho.wasm cadzinho.html cadzinho.data
    - name: Upload the result
      uses: actions/upload-artifact@v4.3.0
      with:
        name: emscripten
        path: emscripten.zip
        retention-days: 5
