name: Test2

on: workflow_dispatch

env:
  MAJOR: 0
  MINOR: 2
  MAN: 1
  YEAR: 2023
jobs:
 test:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        sudo apt-get update
        sudo apt-get install --yes libsdl2-dev libglvnd-dev libglew-dev fuse libfuse2
        sudo gem install fpm
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz
    - name: extract lua
      run: tar zxf lua-5.4.4.tar.gz
    - name: remove main in lua
      run: rm lua-5.4.4/src/lua.c lua-5.4.4/src/luac.c
    - name: copy lua sources 
      run: cp lua-5.4.4/src/* ./src/
    - name: get make file
      run: cp linux/Makefile ./Makefile
    - name: make
      run: make
    - name: download AppImageTool
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
        target: .
    - name: download AppImage asset
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64"
        target: .
    - name: configure AppImageKit
      run: |
        mkdir CadZinho.AppDir
        mkdir CadZinho.AppDir/usr/
        mkdir CadZinho.AppDir/usr/lib
        mkdir CadZinho.AppDir/usr/bin
        mkdir CadZinho.AppDir/usr/bin/share
        mkdir CadZinho.AppDir/usr/bin/share/cadzinho
        mv AppRun-x86_64 CadZinho.AppDir/AppRun
        chmod u+x ./CadZinho.AppDir/AppRun
        cp ./linux/cadzinho.desktop ./CadZinho.AppDir
        cp ./linux/cadzinho.png ./CadZinho.AppDir
        cp ./cadzinho ./CadZinho.AppDir/usr/bin
        cp -r ./lang/ ./CadZinho.AppDir/usr/bin/share/cadzinho/
        fpm -s dir -t deb \
          --name cadzinho \
          --license MIT \
          --version 0.4.0 \
          --architecture all \
          --depends sdl2 --depends glew \
          --description "CadZinho - Minimalist computer aided design (CAD) software" \
          --url "https://github.com/zecruel/CadZinho" \
          --maintainer "Ezequiel Rabelo de Aguiar <ezeq.cruel@gmail.com>" \
          --directories CadZinho.AppDir CadZinho.AppDir
        cp $(ldd cadzinho | grep -o '\W/[^ ]*' | grep 'SDL2\|GLEW\|decor') ./CadZinho.AppDir/usr/lib
        chmod u+x ./appimagetool-x86_64.AppImage
        ./appimagetool-x86_64.AppImage CadZinho.AppDir
    - name: create archive
      run: |
        zip -r linux_appimage CadZinho-x86_64.AppImage LICENSE.txt
    - name: regular linux package
      run: |
        ls
        dpkg -c cadzinho_0.4.0_all.deb
        mkdir ./linux/CadZinho/share/cadzinho
        cp ./cadzinho ./linux/CadZinho
        cp ./LICENSE.txt ./linux/CadZinho/share/cadzinho
        cp -r ./lang/ ./linux/CadZinho/share/cadzinho/
        cd ./linux/CadZinho
        zip -r linux *
    - run: cp ./linux/CadZinho/linux.zip ./
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: |
          linux_appimage.zip
          linux.zip
          cadzinho_0.4.0_all.deb
        retention-days: 5
