name: Test2

on: workflow_dispatch

env:
  MAJOR: 0
  MINOR: 2
  MAN: 1
  YEAR: 2023
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: configure
        run: |
          sudo apt-get update
          sudo apt-get install --yes scrot imagemagick
      - uses: OrbitalOwen/desktop-screenshot-action@0.1
        with:
          file-name: 'screenshot.png'
      - name: Upload the result
        uses: actions/upload-artifact@v3
        with:
          name: uploads
          path: screenshot.png
          retention-days: 5
