name: Test

on: workflow_dispatch

env:
  MAJOR: 0
  MINOR: 4
  MAN: 0
  YEAR: 2023
  LUA_V: 5.4.6
  MESA_V: 23.1.1
  GLEW_V: 2.2.0
  SDL_V: 2.26.5
  HARFBUZZ_V: 8.2.0

jobs:
  win:
   runs-on: windows-latest

   steps:
    - uses: microsoft/setup-msbuild@v1.1
    - uses: actions/checkout@v3
    
    - name: download harfbuzz
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
        url: "https://github.com/harfbuzz/harfbuzz/archive/refs/tags/${{ env.HARFBUZZ_V }}.zip"
        target: ./harfbuzz.zip
    - name: Unzip harfbuzz
      shell: cmd
      run: |
        7z x -y harfbuzz.zip
    - name: compile harfbuzz as static lib
      run: |
        cd harfbuzz-${{ env.HARFBUZZ_V }}\src
        gcc -c harfbuzz.cc -o harf.o -DHB_TINY 
        ar -rcs libharfbuzz.a harf.o
    - name: copy harfbuzz static lib
      run: cp ./harfbuzz-${{ env.HARFBUZZ_V }}/src/libharfbuzz.a ./

    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: libharfbuzz.a
        retention-days: 5
